### ISSUE TITLE
Plugin não redireciona para Itau

### ISSUE THREAD

**Issue by giovannida** [claudiosmweb/wc-itau-shopline#4]
Site http://institutopurim.websitesgoiania.com.br
Quando finalizar o pedido o plugin nao redireciona para a pagina de Itau e recebo esse erro:

Warning: include(/home/websitesgoiania/public_html/institutopurim/wp-content/plugins/woocommerce/templates/payment-instructions.php): failed to open stream: No such file or directory in /home/websitesgoiania/public_html/institutopurim/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 195

Warning: include(): Failed opening '/home/websitesgoiania/public_html/institutopurim/wp-content/plugins/woocommerce/templates/payment-instructions.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/websitesgoiania/public_html/institutopurim/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 195

Por favor preciso de ajuda. Grato

**Comment by claudiosmweb** [comment]
Já respondi sobre isso no wp.org, problema vem de outro plugin.
